[theme]
base="light"
primaryColor= "#9C1C1F"               # Rojo institucional 
backgroundColor= "rgba(55, 55, 55, 1)"            # Fondo negro
secondaryBackgroundColor= "#6e5b0fff"    # Dorado (para secundarios)
textColor="#FFFFFF"                   # Letra blanca
font="Roboto"

# Colores de los encabezados y estilos adicionales
[sidebar]
backgroundColor="#333333"             # Fondo oscuro para la barra lateral
textColor="#FFFFFF"                   # Letra blanca para la barra lateral

[header]
backgroundColor="#F1C40F"             # Encabezados en dorado
textColor="#FFFFFF"                   # Letra blanca para los encabezados

[button]
primaryColor=  "#6e5b0fff"            # Botones dorados
