[theme]
base="light"
primaryColor= "#9C1C1F"               # Rojo institucional 
backgroundColor= "#000000"            # Fondo negro
secondaryBackgroundColor="#F1C40F"    # Dorado (para secundarios)
textColor="#FFFFFF"                   # Letra blanca
font="Roboto"

# Colores de los encabezados y estilos adicionales
[sidebar]
backgroundColor="#333333"             # Fondo oscuro para la barra lateral
textColor="#FFFFFF"                   # Letra blanca para la barra lateral

[header]
backgroundColor="#F1C40F"             # Encabezados en dorado
textColor="#FFFFFF"                   # Letra blanca para los encabezados

[button]
primaryColor="#F1C40F"                # Botones dorados
