[theme]
base="light"
primaryColor= "#6e5b0fff"            # Color marrón oscuro
backgroundColor= "rgba(55, 55, 55, 1)" # Fondo gris oscuro
secondaryBackgroundColor="#9C1C1F"    # Rojo institucional
textColor="#FFFFFF"                   # Texto blanco
font="Roboto"

# Barra lateral
[sidebar]
backgroundColor="#333333"             # Fondo oscuro para la barra lateral
textColor="#FFFFFF"                   # Letra blanca para la barra lateral

# Encabezado
[header]
backgroundColor="#F1C40F"             # Encabezados en dorado
textColor="#FFFFFF"                   # Letra blanca para los encabezados

# Botones
[button]
primaryColor="#F1C40F"                # Botones dorados
